name: Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version Tag'
        required: false
        default: 'v0.0.1'

jobs:
  build:
    strategy:
      matrix:
        os: [ 'windows-latest' ]
        python-version: [ '3.8' ] # '3.5', '3.6', '3.7', '3.8', '3.9', '3.10'

    runs-on: ${{ matrix.os }}

    env:
      # Set your boost version
      BOOST_VERSION: 1.78.0

    name: ${{ github.event.inputs.tag }} python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Switch to Workspace
        run: |
          echo ${{ github.workspace }}
          cd ${{ github.workspace }}

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Install boost
        uses: MarkusJx/install-boost@v2.1.0
        id: install-boost
        with:
          # REQUIRED: Specify the required boost version
          # A list of supported versions can be found here: 
          # https://github.com/actions/boost-versions/blob/main/versions-manifest.json
          boost_version: ${{env.BOOST_VERSION}}
          platform_version: 2019
          toolset: msvc

      # run build command
      - name: Build spout
        run: |
          echo "boost root:"
          ls $BOOST_ROOT
          cd SpoutSDK
          mkdir build
          msbuild "Spout for Python.sln" /property:Configuration=Release /p:OutputPath=build /p:AdditionalIncludePaths="$BOOST_ROOT"
          ls build
          ls x64\Release

      # upload dist
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        # if: ${{ false }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*.whl
          tag: ${{ github.event.inputs.tag }}
          release_name: "Version ${{ github.event.inputs.tag }}"
          body: "Prebuilt syphonpy wheel packages version ${{ github.event.inputs.tag }}."
          overwrite: true
          file_glob: true